FIND_PATH(KGLLIB_INCLUDE_DIR kgllib/kgllib.h )

FIND_LIBRARY(KGLLIB_LIBRARY NAMES kgllib )
FIND_LIBRARY(KGLLIB_EXTRAS_LIBRARY NAMES kgllib-extras )

IF (KGLLIB_INCLUDE_DIR AND KGLLIB_LIBRARY)
   SET(KGLLIB_FOUND TRUE)
ENDIF (KGLLIB_INCLUDE_DIR AND KGLLIB_LIBRARY)


IF (KGLLIB_FOUND)
   IF (NOT KGLLib_FIND_QUIETLY)
      MESSAGE(STATUS "Found KGLLib: ${KGLLIB_LIBRARY}")
   ENDIF (NOT KGLLib_FIND_QUIETLY)
ELSE (KGLLIB_FOUND)
   IF (KGLLib_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find KGLLib")
   ENDIF (KGLLib_FIND_REQUIRED)
ENDIF (KGLLIB_FOUND)
